### PR TITLE
Added the option to completely ignore a property in dapper

### PR DESCRIPTION
**Pull request by thomasbargetz**

### CODE REVIEW

**Comment by henkmollema** [comment]
Thanks for your contribution @thomasbargetz. I understand that the current implementation of ignored properties is not correct. 

Although I don't like leaving users with a choice whether they want to use Dapper's default type map through the public `AddMap<TEntity>()` API. Also, not using the `DefaultTypeMap` requires you to define a mapping between _every_ property and column or it will not map the property at all. That might result in unexpected behavior.

I'd rather not support ignored properties than support it partially (and potentially buggy). _Or_ use a better fallback mechanism for using the default type map. Eg: look for a mapping, if it does not exists: use `DefaultTypeMap`; if it does exists but `Ignored == true`: skip; otherwise return the property.

**Comment by thomasbargetz** [comment]
Thanks for your response @henkmollema. I think, skipping the mapping if the Ignored flag is true is indeed a better way. To be honest, when I've looked into the code I didn't see how I could do that in the MultiTypeMap.GetMember method. The structure of the method (iterating over all mappers) doesn't allow me to do that, because the GetMember method of the ITypeMap interface returns an IMemberMap  instance, which doesn't provide any information about ignoring....

Extending the IMemberMap would be an option, but I don't know if it's a good idea to extend the base interface just for ignoring ...


Besides the ignoring problem, my second commit is a real bugfix, because the original code just looksup the first mapping, if this one has set the Ignored flag to true, no mapping will be returned at all.

**Comment by henkmollema** [comment]
`IMemberMap` is a Dapper type, so changing that will be difficult.

Regarding the current implementation: I don't see how that is a bug. It looks up the first mapping, which matches the name of the current column, if `Ignored == true` we skip it and return `null` in stead. How does that differ from looking up a mapping which matches the name of the current column and `Ignored == false` and if that is not found, also return `null`.

**Comment by thomasbargetz** [comment]
Let me explain it with an example:

	class A {
		// lat lon position as ulong
		public ulong PositionAsInt64 {get; set;}
		
		// lat lon as lat lon object
		public LatLon Position {get; set;}
	}

The table has a column named "position" which stores the lat lon position as an ulong.

The mapping:

	Map(a => a.Position).Ignore();
	Map(a => a.PositionAsInt64).ToColumn("position");

Now the lookup finds the mapping for Position, which has been set to ignore. Therefore no mapping will be found. But actually PositionAsInt64 maps to the column "position".

**Comment by henkmollema** [comment]
Ah, that makes sense. Thanks for the explanation. Can you create a new PR with that change? This commit: https://github.com/thomasbargetz/Dapper-FluentMap/commit/aff9f873df8ab603ad4b2327370cd27b4c61ed88.

**Comment by thomasbargetz** [comment]
@henkmollema check my new commit. It's now possible to ignore a property without loosing the default mapping behaviour of dapper.

**Comment by thomasbargetz** [comment]
@henkmollema sigh... forgot to fetch correct mapping. fixed that in the latest commit... I guess some more tests would be nice :-)

**Pull request closed without merging**
